/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikimiPackage;

import java.util.Arrays;

/**
 *
 * @author Hp
 */
public class AplikimiJFrame extends javax.swing.JFrame {
      String ComNet ;
      String emri;
      int mosha;
      int numri;
      String telefon;
      
      
      
      
    /**
     * Creates new form AplikimiJFrame
     */
    public AplikimiJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_emri = new javax.swing.JLabel();
        txf_emri = new javax.swing.JTextField();
        btnApliko = new javax.swing.JButton();
        label_output = new javax.swing.JLabel();
        jLabel1_mbiemri = new javax.swing.JLabel();
        txf_mbiemri = new javax.swing.JTextField();
        jLabel1_mosha = new javax.swing.JLabel();
        txf_mosha = new javax.swing.JTextField();
        jLabel1_komuna = new javax.swing.JLabel();
        txf_komuna = new javax.swing.JTextField();
        jLabel1_email = new javax.swing.JLabel();
        txf_email = new javax.swing.JTextField();
        txf_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txf_confirmpass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txf_pozita = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txf_universiteti = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txf_dega = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txf_mesatarja = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txf_qyteti = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txf_numri = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txf_area = new javax.swing.JTextArea();
        jLabel11_password = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txf_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_emri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1_emri.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1_emri.setText("Emri:");

        txf_emri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_emriActionPerformed(evt);
            }
        });
        txf_emri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txf_emriKeyPressed(evt);
            }
        });

        btnApliko.setBackground(new java.awt.Color(204, 255, 204));
        btnApliko.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApliko.setForeground(new java.awt.Color(102, 102, 255));
        btnApliko.setText("Apliko");
        btnApliko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAplikoMouseClicked(evt);
            }
        });
        btnApliko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplikoActionPerformed(evt);
            }
        });

        label_output.setBackground(new java.awt.Color(204, 255, 204));
        label_output.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1_mbiemri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1_mbiemri.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1_mbiemri.setText("Mbiemri:");

        jLabel1_mosha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1_mosha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1_mosha.setText("Mosha:");

        jLabel1_komuna.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1_komuna.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1_komuna.setText("Komuna:");

        txf_komuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_komunaActionPerformed(evt);
            }
        });

        jLabel1_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1_email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1_email.setText("E-mail:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Adresa:");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aplikim Pune ne UBT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Pozita e aplikimit:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Universiteti:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Dega:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nota mesatare:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Qyteti:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Confirm:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nr.telefonit:");

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Anulo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txf_area.setColumns(20);
        txf_area.setRows(5);
        jScrollPane1.setViewportView(txf_area);

        jLabel11_password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11_password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11_password.setText("Password:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1_email, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jLabel1_mosha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_emri, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1_komuna, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_emri, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_mosha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_komuna, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_confirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_numri, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txf_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(txf_email, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_output, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApliko, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_dega, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_universiteti, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_pozita, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_qyteti, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_mesatarja, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_emri, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txf_emri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txf_pozita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txf_mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_mosha)
                            .addComponent(txf_mosha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txf_dega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_komuna)
                            .addComponent(txf_komuna, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txf_mesatarja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_qyteti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1_email)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txf_universiteti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_numri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_confirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_output, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnApliko, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_emriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_emriActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txf_emriActionPerformed

    private void txf_emriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_emriKeyPressed
     
           
    }//GEN-LAST:event_txf_emriKeyPressed

    private void btnAplikoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAplikoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplikoMouseClicked

    private void btnAplikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplikoActionPerformed
        // TODO add your handling code here:
      
         if (txf_emri.getText().equals(""))
         {
          label_output.setText("Fusha Emrit eshte e zbrazet");    
               }
         else if (txf_emri.getText().length()<=2)
                 {
                 label_output.setText("Fusha Emri nuk eshte valide");
                 }
         
              
          else  if (txf_mbiemri.getText().equals("")){
          label_output.setText("Fusha Mbiemri eshte e zbrazet");    
               }
              else if (txf_mbiemri.getText().length()<=2)
                 {
                 label_output.setText("Fusha Mbiemri nuk eshte valide");
                 }
            
         else  if (txf_mosha.getText().equals("")){
          label_output.setText("Fusha Mosha eshte e zbrazet");    
               }
              else if (txf_mosha.getText().length()<=2)
                 {
                 label_output.setText("Fusha Mosha nuk eshte valide");
                 }
              
              emri = txf_mosha.getText();
              int mosha = Integer.parseInt(emri);
             
         if(mosha < 18) {
         label_output.setText("Nuk keni moshen e mjaftueshme per aplikim");
         }
          
         else if (txf_komuna.getText().equals(""))
         {
             label_output.setText("Fusha Komuna eshte e zbrazet");
         }   
         else if (txf_komuna.getText().length()<=2)
         {
             label_output.setText("Fusha komuna nuk eshte e valide");
         }
         else  if (txf_area.getText().equals("")){
               label_output.setText("Fusha Adresa eshte e zbrazet");    
          }
          else if (txf_area.getText().length()<=2)
          {
                 label_output.setText("Fusha Adresa nuk eshte valide");
           }            
          else  if (txf_pozita.getText().equals("")){
               label_output.setText("Fusha Pozita e aplikimit eshte e zbrazet");    
          }
           else if (txf_pozita.getText().length()<=2)
          {
                 label_output.setText("Fusha Pozita e aplikimit nuk eshte valide");
           }
          else  if (txf_universiteti.getText().equals("")){
               label_output.setText("Fusha Universiteti eshte e zbrazet");    
          }
           else if (txf_universiteti.getText().length()<=2)
          {
                 label_output.setText("Fusha Universiteti nuk eshte valide");
           }
           else  if (txf_dega.getText().equals("")){
               label_output.setText("Fusha Dega eshte e zbrazet");    
          }
           else if (txf_dega.getText().length()<=2)
          {
                 label_output.setText("Fusha Dega nuk eshte valide");
           }
           else  if (txf_qyteti.getText().equals("")){
               label_output.setText("Fusha Qyteti eshte e zbrazet");    
          }
           else if (txf_qyteti.getText().length()<=2)
          {
                 label_output.setText("Fusha Qyteti nuk eshte valide");
           }
           
          else  if (txf_numri.getText().equals("")){
          label_output.setText("Fusha Nr.telefon eshte e zbrazet");    
               }
          telefon = txf_mosha.getText();
              int numri = Integer.parseInt(telefon);
              
               if (txf_numri.getText().length()<=6)
                 {
                 label_output.setText("Numri juaj nuk funksionon");
                 }
          else  if (txf_mesatarja.getText().equals("")){
          label_output.setText("Fusha Nota mesatare eshte e zbrazet");    
               } 
          else if (txf_password.getText().equals(""))
          {
              label_output.setText("Fusha Password eshte e zbrazet");
          }
          else if (txf_password.getText().length()<8)
          {
              label_output.setText("Passwordi duhet te kete me shume se 8 karaktere");
          }
          else if (txf_confirmpass.getText().equals(""))
          {
              label_output.setText("Konfirmojeni Passwordin");
          }
         else if (!(new String(txf_password.getPassword()).equals(new String(txf_confirmpass.getPassword())))) {
             {
             label_output.setText("Passwordi nuk eshte konfirmuar");
         }

            else if (txf_email.getText().equals(""))
          {
              label_output.setText("Fusha E-email eshte e  zbrazet");
          }
        else if (txf_email.getText().indexOf("@") <=0 ) 
         {
             label_output.setText("Fusha E-mail nuk eshte valide");
             
         }
        else if (!txf_email.getText().endsWith(".com") && !txf_email.getText().endsWith(".info") ) 
         {
             label_output.setText("Fusha E-mail nuk eshte valide");
             
         }
         else  if (txf_ID.getText().equals("")){
               label_output.setText("Fusha ID eshte e zbrazet");    
          }
           else if (txf_ID.getText().length()<=5)
          {
                 label_output.setText("Fusha ID nuk eshte valide");
           }
          else  if (txf_qyteti.getText().equals("")){
               label_output.setText("Fusha Qytetii eshte e zbrazet");    
          }
           else if (txf_qyteti.getText().length()<=2)
          {
                 label_output.setText("Fusha Qyteti nuk eshte valide");
           }  
           else {
             label_output.setText("Aplikimi i juaj eshte kryer me sukses");
             

              }

               
         
        
        
               
    }//GEN-LAST:event_btnAplikoActionPerformed

    private void txf_komunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_komunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_komunaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikimiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikimiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikimiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikimiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikimiJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApliko;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11_password;
    private javax.swing.JLabel jLabel1_email;
    private javax.swing.JLabel jLabel1_emri;
    private javax.swing.JLabel jLabel1_komuna;
    private javax.swing.JLabel jLabel1_mbiemri;
    private javax.swing.JLabel jLabel1_mosha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_output;
    private javax.swing.JTextField txf_ID;
    private javax.swing.JTextArea txf_area;
    private javax.swing.JPasswordField txf_confirmpass;
    private javax.swing.JTextField txf_dega;
    private javax.swing.JTextField txf_email;
    private javax.swing.JTextField txf_emri;
    private javax.swing.JTextField txf_komuna;
    private javax.swing.JTextField txf_mbiemri;
    private javax.swing.JTextField txf_mesatarja;
    private javax.swing.JTextField txf_mosha;
    private javax.swing.JTextField txf_numri;
    private javax.swing.JPasswordField txf_password;
    private javax.swing.JTextField txf_pozita;
    private javax.swing.JTextField txf_qyteti;
    private javax.swing.JTextField txf_universiteti;
    // End of variables declaration//GEN-END:variables
}
